@Lab01_HostAddress = https://localhost:7155

GET {{Lab01_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Lab01_HostAddress}}/api/students
Content-Type: application/json

{
  //Student
}

###

@id=0
DELETE {{Lab01_HostAddress}}/api/students/{{id}}

###

GET {{Lab01_HostAddress}}/api/students/{{id}}

###

PUT {{Lab01_HostAddress}}/api/students/{{id}}
Content-Type: application/json

{
  //Student
}

###

@name=string
GET {{Lab01_HostAddress}}/api/Students/{{name}}

###
